import './models/player.dart';

const DUMMY_PLAYERS = const [
  Player(
    name: 'Jaysel Dela Cruz',
    age: 20,
    position: 'Point Guard',
    height: 175,
    contactNumber: 07123456789,
    grade: 'D',
    id: 'P1',
    image: '',
  ),
  Player(
    name: 'Stephen Curry',
    age: 32,
    position: 'Point Guard',
    height: 191,
    contactNumber: 07123456789,
    grade: 'S',
    id: 'P2',
    image: 'assets/images/avatars/stephen_curry.png',
  ),
  Player(
    name: 'Jayson Tatum',
    age: 22,
    position: 'Power Forward',
    height: 203,
    contactNumber: 07123456789,
    grade: 'A',
    id: 'P3',
    image: 'assets/images/avatars/jayson_tatum.png',
  ),
  Player(
    name: 'Nikola Jokic',
    age: 25,
    position: 'Center',
    height: 213,
    contactNumber: 07123456789,
    grade: 'S',
    id: 'P4',
    image: 'assets/images/avatars/nikola_jokic.png',
  ),
  Player(
    name: 'Kevin Durant',
    age: 31,
    position: 'Small Forward',
    height: 208,
    contactNumber: 07123456789,
    grade: 'S',
    id: 'P5',
    image: 'assets/images/avatars/kevin_durant.png',
  ),
  Player(
    name: 'Danny Green',
    age: 33,
    position: 'Shooting Guard',
    height: 197,
    contactNumber: 07123456789,
    grade: 'B',
    id: 'P6',
    image: 'assets/images/avatars/danny_green.png',
  ),
];
